
name: 'chris_train'
version: '1.0'
profile: 'chris_train'
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"


models:
  chris_train:
    example:
        materialized: view
    staging:
        stg_orders:
            schema: "staging"
            materialized: table
              
